# Generated by Django 3.2.8 on 2021-10-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211014_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='complement',
            field=models.CharField(blank=True, max_length=50, verbose_name='complement'),
        ),
    ]
